# config.yaml
executionOrder:
  continueOnFailure: true
  flowsOrder:
    - login-failure
    - login-success-student
    - mark_attendance
    - confirm_marked_attendance
    - login-success-coordinator


